In [1]:
import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ["GROQ_API_KEY"]

print("API key loaded successfully.")

API key loaded successfully.

In [2]:
from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1"
)

MODEL = "llama-3.3-70b-versatile"

print("Client ready.")

Client ready.

In [3]:
def ask_llm(
    user_prompt,
    system_prompt="You are a helpful assistant.",
    temperature=0.7,
    max_tokens=500
):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )

    return response

In [4]:
response = ask_llm(
    "What are three benefits of saving money?"
)

print(response.choices[0].message.content)
print("\nToken usage:")
print(response.usage)

Saving money can have numerous benefits. Here are three of them:

1. **Financial Security**: Saving money provides a sense of financial security, as it creates a cushion for unexpected expenses, emergencies, or financial setbacks. Having a safety net can reduce stress and anxiety, allowing you to feel more secure about your financial future.

2. **Long-term Goals**: Saving money enables you to work towards long-term goals, such as buying a house, funding your education, or retiring comfortably. By setting aside a portion of your income regularly, you can make progress towards achieving your goals and creating a better future for yourself.

3. **Reduced Debt and Financial Stress**: Saving money can help you avoid debt and reduce financial stress. By having a savings fund, you can avoid borrowing money from lenders or using credit cards, which can lead to high-interest debt and financial difficulties. This, in turn, can improve your overall well-being and provide peace of mind.

These are just a few benefits of saving money, but there are many more advantages to developing a savings habit.

Token usage:
CompletionUsage(completion_tokens=213, prompt_tokens=49, total_tokens=262, completion_tokens_details=None, prompt_tokens_details=None, queue_time=0.051118438, prompt_time=0.004999421, completion_time=0.544044019, total_time=0.54904344)

In [5]:
question = "Suggest a name for a savings product for market traders in Accra."

# Temperature 0.0
print("===== TEMPERATURE 0.0 =====")

for i in range(5):
    response = ask_llm(
        question,
        temperature=0.0,
        max_tokens=100
    )
    print(f"{i+1}. {response.choices[0].message.content}")


# Temperature 1.2
print("\n===== TEMPERATURE 1.2 =====")

for i in range(5):
    response = ask_llm(
        question,
        temperature=1.2,
        max_tokens=100
    )
    print(f"{i+1}. {response.choices[0].message.content}")

===== TEMPERATURE 0.0 =====
1. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language
2. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language
3. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language
4. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Sika Kokoo**: "Sika" means "money" in the Akan language, and "Kokoo" means "gather" or "collect
5. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **TradeUp Savings**: This name suggests that the savings product will help traders "trade up" and improve their financial situation.
3. **Sika Kokoo**: "Sika" means "money" in the Akan language, which is widely spoken

===== TEMPERATURE 1.2 =====
1. Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with traders.
2. **TradeSafe**: This name conveys the idea of securing one's trade and financial well-being.
3. **Sika Kurom**: "Sika" means "money" in the Akan language, and "Kurom" means "safe"
2. Here are some name suggestions for a savings product tailored to market traders in Accra:

1. **Susu Plus**: "Susu" is a traditional savings scheme in Ghana, and adding "Plus" suggests additional benefits.
2. **MarketVault**: This name conveys a sense of security and protection for traders' savings.
3. **TraderSave**: Simple and straightforward, this name highlights the product's purpose.
4. **Accra Thrive**: This name positions the savings product as a
3. For a savings product targeting market traders in Accra, here are some name suggestions that might appeal to them:

1. **Makola Save**: "Makola" is a popular marketplace in Accra, so this name could resonate with market traders.
2. **Traders' Treasure**: This name conveys the idea of saving and accumulating treasure, which could motivate traders to save.
3. **Accra Aman**: "Aman" means "peace" in the Akan language
4. Here are a few name suggestions for a savings product targeting market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with market traders and evoke a sense of familiarity.
2. **Traders' Vault**: This name conveys a sense of security and protection for the traders' savings, which is essential for building trust.
3. **Accra Thrive**: This name suggests that the savings product
5. Here are a few suggestions for a savings product tailored to market traders in Accra:

1. **Maakye Savings**: "Maakye" is a Ghanaian term that means "good morning" or "morning profits," which could resonate with market traders who start their day early.
2. **Sika Kokoo**: "Sika" means "money" in the Akan language, and "Kokoo" means "happiness" or "profit." This name combines the

In [6]:
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

6 letters loaded.

In [7]:
for letter_id, letter in LETTERS.items():
    print(f"\n{'='*60}")
    print(letter_id)
    print('='*60)
    print(letter)

============================================================
L001
============================================================
Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.

============================================================
L002
============================================================
Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.

============================================================
L003
============================================================
Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.

============================================================
L004
============================================================
Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.

============================================================
L005
============================================================
Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.

============================================================
L006
============================================================
Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.

In [8]:
SUMMARY_PROMPT_V1 = "Summarize this loan application:\n\n{letter_text}"

In [9]:
for letter_id in ["L002", "L006"]:
    print(f"\n{'='*60}")
    print(f"{letter_id} - V1")
    print("="*60)

    prompt = SUMMARY_PROMPT_V1.format(letter_text=LETTERS[letter_id])

    response = ask_llm(
        prompt,
        temperature=0.7,
        max_tokens=200
    )

    print(response.choices[0].message.content)

============================================================
L002 - V1
============================================================
Kwame Boateng, a commercial driver in Kumasi, is applying for a loan of GHS 25,000. He needs the money to:

1. Repair his trotro (minibus) engine
2. Settle personal debts

He expects his business to improve after the festive season and is willing to repay the loan when he can, but does not have collateral to offer at the moment. He is seeking urgent assistance.

============================================================
L006 - V1
============================================================
Kofi, a 22-year-old, is applying for a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business. He has no prior experience or collateral, but claims to be "business-minded" and "trustworthy". He plans to repay the loan within one year, expecting his businesses to be successful by then.

In [10]:
SUMMARY_SYSTEM_V2 = """
You are an assistant to a microfinance loan officer.

Summarize loan applications into a short factual brief that a busy loan officer
can quickly read.

Rules:
- Be factual and neutral.
- Use only information stated in the application.
- Do not invent, assume, or infer missing facts.
- Do not make a loan approval or rejection decision.
- Keep the summary to 3-4 sentences.
- Include the applicant's name, requested amount, purpose of the loan,
  relevant business information, repayment information, and collateral/
  guarantor information when stated.
"""

In [11]:
SUMMARY_PROMPT_V2 = """
Summarize this loan application according to the instructions.

Loan application:
{letter_text}
"""

In [12]:
for letter_id in ["L002", "L006"]:
    print(f"\n{'='*60}")
    print(f"{letter_id} - V2")
    print("="*60)

    prompt = SUMMARY_PROMPT_V2.format(letter_text=LETTERS[letter_id])

    response = ask_llm(
        prompt,
        system_prompt=SUMMARY_SYSTEM_V2,
        temperature=0.0,
        max_tokens=200
    )

    print(response.choices[0].message.content)

============================================================
L002 - V2
============================================================
Kwame Boateng, a commercial driver in Kumasi, has applied for a loan of GHS 25,000 to repair his trotro engine and settle personal debts. He mentions that his business has been slow, but expects it to improve after the festive season. Mr. Boateng does not specify a repayment plan, but states he can pay back the loan when he has the money. He also notes that he does not have collateral to offer at the moment.

============================================================
L006 - V2
============================================================
Kofi is applying for a loan of GHS 50,000 to start three businesses: a car washing business, a provision shop, and a phone import business. The applicant, who is 22 years old, has not yet established any of these businesses. Kofi plans to repay the loan in one year, expecting the businesses to be successful by then. No collateral is offered, but the applicant claims to be trustworthy.

In [13]:
EXTRACT_SYSTEM_PROMPT = """
You are a data extraction assistant for a microfinance loan officer.

Extract information from the loan application and return ONLY a valid JSON object.

The JSON must contain EXACTLY these keys:

{
  "applicant_name": "string",
  "amount_ghs": "number",
  "purpose": "string",
  "monthly_profit_ghs": "number or null",
  "has_collateral_or_guarantor": "boolean",
  "repayment_months": "number or null"
}

Rules:
- Extract only information explicitly stated in the application.
- Do not guess or infer missing information.
- If a field is not stated, use null.
- amount_ghs must be a number, not a string.
- monthly_profit_ghs must be a number or null.
- repayment_months must be a number or null.
- has_collateral_or_guarantor is true if the applicant explicitly mentions
  collateral or a guarantor; otherwise false.
- Return ONLY JSON. Do not include explanations or markdown.
"""

In [14]:
EXAMPLE_LETTER = """
My name is Ama. I run a small bakery and have operated for five years.
I am requesting GHS 6,000 to buy a new oven. My monthly profit is GHS 1,200.
My brother will guarantee the loan. I plan to repay it over 10 months.
"""

EXAMPLE_JSON = """
{
  "applicant_name": "Ama",
  "amount_ghs": 6000,
  "purpose": "buy a new oven",
  "monthly_profit_ghs": 1200,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}
"""

In [15]:
EXTRACT_PROMPT = """
Extract the required information from the loan application below.

Example:

Loan application:
{example_letter}

Correct JSON:
{example_json}

Now extract information from this application:

Loan application:
{letter_text}

Return ONLY the JSON object.
"""

In [16]:
import json

def extract_fields(letter_text, temperature=0.0):
    prompt = EXTRACT_PROMPT.format(
        example_letter=EXAMPLE_LETTER,
        example_json=EXAMPLE_JSON,
        letter_text=letter_text
    )

    try:
        response = ask_llm(
            prompt,
            system_prompt=EXTRACT_SYSTEM_PROMPT,
            temperature=temperature,
            max_tokens=300
        )

        result = response.choices[0].message.content.strip()

        # Remove markdown JSON fences if present
        if result.startswith("```json"):
            result = result[7:]

        if result.startswith("```"):
            result = result[3:]

        if result.endswith("```"):
            result = result[:-3]

        result = result.strip()

        return json.loads(result)

    except json.JSONDecodeError:
        print("WARNING: Model returned invalid JSON.")
        print("Raw response:", result)
        return None

    except Exception as e:
        print("WARNING:", e)
        return None

In [17]:
result = extract_fields(LETTERS["L001"])

print(result)

{'applicant_name': 'Akosua Mensah', 'amount_ghs': 8000, 'purpose': 'buy a deep freezer and expand into frozen foods', 'monthly_profit_ghs': 900, 'has_collateral_or_guarantor': True, 'repayment_months': 20}

In [18]:
import pandas as pd

extracted_results = []

for letter_id, letter_text in LETTERS.items():
    result = extract_fields(letter_text)

    if result is not None:
        result["letter_id"] = letter_id
    else:
        result = {
            "letter_id": letter_id,
            "applicant_name": None,
            "amount_ghs": None,
            "purpose": None,
            "monthly_profit_ghs": None,
            "has_collateral_or_guarantor": None,
            "repayment_months": None
        }

    extracted_results.append(result)

extracted_df = pd.DataFrame(extracted_results)

extracted_df = extracted_df[
    [
        "letter_id",
        "applicant_name",
        "amount_ghs",
        "purpose",
        "monthly_profit_ghs",
        "has_collateral_or_guarantor",
        "repayment_months"
    ]
]

display(extracted_df)

,letter_id,applicant_name,amount_ghs,purpose,monthly_profit_ghs,has_collateral_or_guarantor,repayment_months
0,L001,Akosua Mensah,8000,buy a deep freezer and expand into frozen foods,900.0,True,20.0
1,L002,Kwame Boateng,25000,repair my trotro engine and settle some person...,NaN,False,NaN
2,L003,Efua Darko,15000,purchase two industrial sewing machines and fa...,2800.0,True,15.0
3,L004,Yaw Owusu,12000,for feed and 500 new layers,1500.0,True,18.0
4,L005,Adenta Women's Weaving Cooperative,30000,buy a bulk order of yarn directly from the fac...,NaN,True,16.0
5,L006,Kofi,50000,"start a car washing business, a provision shop...",NaN,False,12.0

In [19]:
BRIEF_SYSTEM_PROMPT = """
You are an assistant supporting a microfinance loan officer.

Your job is to analyze a loan application and provide a neutral
decision-support brief.

The final loan decision must always be made by a human loan officer.

Use ONLY information contained in the loan application and extracted data.
Do not invent facts or make assumptions.

Your response must contain exactly these sections:

1. Strengths
- List positive factors supported by the application.

2. Risks / Red flags
- List relevant financial, business, repayment, or other risks supported
  by the application.
- Do not exaggerate or invent risks.

3. Missing information
- List important information that is not provided and should be requested
  by the loan officer.

4. Suggested next step
- Recommend an appropriate action such as requesting documents,
  inviting the applicant for an interview, or flagging the application
  for senior review.
- NEVER say "approve" or "reject".
"""

In [20]:
BRIEF_PROMPT = """
Prepare a decision-support brief for the following loan application.

ORIGINAL APPLICATION:
{letter_text}

EXTRACTED INFORMATION:
{extracted_json}

Remember: the final loan decision must be made by a human.
Do not approve or reject the application.
"""

In [21]:
import json

def generate_brief(letter_text, extracted_data):
    prompt = BRIEF_PROMPT.format(
        letter_text=letter_text,
        extracted_json=json.dumps(extracted_data, indent=2)
    )

    response = ask_llm(
        prompt,
        system_prompt=BRIEF_SYSTEM_PROMPT,
        temperature=0.0,
        max_tokens=500
    )

    return response.choices[0].message.content

In [22]:
briefs = {}

for letter_id in LETTERS:
    extracted_row = extracted_df[
        extracted_df["letter_id"] == letter_id
    ].iloc[0].to_dict()

    briefs[letter_id] = generate_brief(
        LETTERS[letter_id],
        extracted_row
    )

print("Generated briefs for all six applications.")

Generated briefs for all six applications.

In [23]:
for letter_id in ["L001", "L002", "L006"]:
    print(f"\n{'='*70}")
    print(f"DECISION-SUPPORT BRIEF: {letter_id}")
    print("="*70)
    print(briefs[letter_id])

======================================================================
DECISION-SUPPORT BRIEF: L001
======================================================================
## 1. Strengths
- The applicant, Akosua Mensah, has 12 years of experience selling provisions at Makola Market, indicating a stable and established business.
- She has a consistent profit of GHS 900 per month from her current stall, showing a viable income stream.
- Akosua has saved GHS 2,500 over two years with the susu scheme without missing a contribution, demonstrating her ability to manage savings and potentially repay a loan.
- She has a guarantor, her sister, who is a teacher, providing an additional layer of security for the loan.
- The proposed repayment plan of GHS 450 monthly over 20 months is outlined, showing a clear intention to repay the loan.

## 2. Risks / Red flags
- The loan amount of GHS 8,000 is significant compared to the applicant's monthly profit of GHS 900, which might pose a risk if the expansion into frozen foods does not generate enough additional income to cover the loan repayments.
- There is no detailed information provided about the market demand for frozen foods at Makola Market or the potential competition, which could affect the success of the expansion.
- The application does not include a detailed breakdown of how the GHS 8,000 will be used (e.g., cost of the deep freezer, initial stock of frozen foods, etc.), which could be important for assessing the viability of the expansion plan.

## 3. Missing information
- Detailed market analysis or research on the demand for frozen foods at Makola Market.
- A breakdown of the costs associated with the expansion (deep freezer, initial inventory, marketing, etc.).
- Information about the sister's (guarantor's) financial stability and ability to cover the loan if the applicant defaults.
- The applicant's current debt obligations, if any, to assess her overall financial health and ability to take on additional debt.

## 4. Suggested next step
- Request additional documentation and information to fill in the gaps identified, such as a detailed business plan for the expansion into frozen foods, market research, and a breakdown of the costs.
- Invite Akosua Mensah for an interview to discuss her application, the expansion plans, and to gather more information about her business and financial situation.
- Consider requesting financial documents or records to verify the applicant's monthly profit and to assess her overall financial health.

======================================================================
DECISION-SUPPORT BRIEF: L002
======================================================================
## 1. Strengths
- The applicant, Kwame Boateng, has a clear purpose for the loan, which is to repair his trotro engine and settle personal debts, indicating a potential for business improvement post-repair.
- The applicant is a commercial driver, suggesting an existing income stream, albeit currently slow.

## 2. Risks / Red flags
- The applicant mentions that business has been slow, which could impact his ability to repay the loan.
- There is no specified repayment plan or timeline provided by the applicant.
- The lack of collateral or a guarantor increases the risk for the lender.
- The applicant's statement that he can pay back "whenever the money comes" is vague and does not provide a clear repayment commitment.

## 3. Missing information
- Detailed financial information, such as monthly profits or expenses, is not provided.
- A specific repayment plan, including the number of months to repay the loan and the amount of each installment, is missing.
- Information about the applicant's credit history or previous loan experiences is not available.
- The current condition and value of the trotro, as well as the estimated cost of repairs, are not specified.

## 4. Suggested next step
- The loan officer should request additional financial information from the applicant, including detailed income and expense records, to assess the viability of the business and the applicant's repayment capacity.
- An interview with the applicant could provide more insight into his business plan, the potential for increased income post-repair, and his understanding of the loan terms.
- The loan officer may also want to discuss possible collateral options or guarantor arrangements with the applicant to mitigate the risk.

======================================================================
DECISION-SUPPORT BRIEF: L006
======================================================================
## 1. Strengths
- The applicant, Kofi, expresses enthusiasm and energy for starting multiple businesses, which could be a positive indicator of his motivation and potential for success.
- The diversity of business ventures (car washing, provision shop, and importing phones) suggests an attempt to mitigate risk by not relying on a single income stream.

## 2. Risks / Red flags
- The applicant lacks experience in the proposed businesses, as indicated by not having started any of them yet.
- There is no provided financial information, such as projected monthly profits or a detailed business plan, to assess the viability of the businesses.
- The absence of collateral or a guarantor increases the risk for the lender.
- The repayment plan is based on the businesses "booming" within a year, which is an uncertain and potentially unrealistic expectation.

## 3. Missing information
- Detailed business plans for each of the proposed ventures.
- Projected income statements and cash flow projections for the businesses.
- Information on the applicant's educational background, business training, or any relevant skills.
- Market research or analysis to support the demand for the proposed services and products.
- A clear repayment schedule and strategy beyond the general statement of paying back in one year.

## 4. Suggested next step
- Request a comprehensive business plan from the applicant, including market analysis, financial projections, and management structure for each business.
- Invite the applicant for an interview to discuss the application in more detail, assess his understanding of the proposed businesses, and evaluate his preparedness for the challenges associated with entrepreneurship.
- Consider requesting additional documentation, such as a personal credit report or references, to further assess the applicant's creditworthiness.

In [24]:
# Fields we need to evaluate
fields = [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

gold_ids = ["L001", "L003", "L006"]

accuracy_results = []

for field in fields:
    row = {"field": field}
    correct = 0

    for letter_id in gold_ids:
        predicted = extracted_df.loc[
            extracted_df["letter_id"] == letter_id, field
        ].iloc[0]

        expected = GOLD[letter_id][field]

        # Names are case-insensitive
        if field == "applicant_name":
            is_correct = (
                str(predicted).strip().lower()
                == str(expected).strip().lower()
            )

        # Purposes can have slightly different wording,
        # so compare after normalizing the text.
        elif field == "purpose":
            predicted_text = str(predicted).lower().strip()
            expected_text = str(expected).lower().strip()

            is_correct = (
                predicted_text == expected_text
                or expected_text in predicted_text
                or predicted_text in expected_text
            )

        else:
            is_correct = predicted == expected

        row[letter_id] = is_correct

        if is_correct:
            correct += 1

    row["accuracy"] = correct / len(gold_ids)
    accuracy_results.append(row)

accuracy_df = pd.DataFrame(accuracy_results)

display(accuracy_df)

                         field   L001  L003   L006  accuracy
0               applicant_name   True  True   True  1.000000
1                   amount_ghs   True  True   True  1.000000
2                      purpose  False  True  False  0.333333
3           monthly_profit_ghs   True  True  False  0.666667
4  has_collateral_or_guarantor   True  True   True  1.000000
5             repayment_months   True  True   True  1.000000

In [25]:
import json

def run_reliability_test(letter_id, temperature, runs=5):
    results = []
    valid_results = []

    for i in range(runs):
        result = extract_fields(
            LETTERS[letter_id],
            temperature=temperature
        )

        results.append(result)

        if result is not None:
            valid_results.append(
                json.dumps(result, sort_keys=True)
            )

    unique_results = set(valid_results)

    return {
        "temperature": temperature,
        "total_runs": runs,
        "valid_json": len(valid_results),
        "unique_valid_outputs": len(unique_results),
        "identical_outputs": (
            len(valid_results) > 0 and len(unique_results) == 1
        ),
        "results": results
    }

In [26]:
temp_0_results = run_reliability_test(
    "L004",
    temperature=0.0
)

temp_1_results = run_reliability_test(
    "L004",
    temperature=1.0
)

print("===== TEMPERATURE 0.0 =====")
print("Valid JSON:", temp_0_results["valid_json"])
print("Unique valid outputs:", temp_0_results["unique_valid_outputs"])
print("All identical:", temp_0_results["identical_outputs"])

print("\n===== TEMPERATURE 1.0 =====")
print("Valid JSON:", temp_1_results["valid_json"])
print("Unique valid outputs:", temp_1_results["unique_valid_outputs"])
print("All identical:", temp_1_results["identical_outputs"])

===== TEMPERATURE 0.0 =====
Valid JSON: 5
Unique valid outputs: 1
All identical: True

===== TEMPERATURE 1.0 =====
Valid JSON: 5
Unique valid outputs: 1
All identical: True

In [27]:
print("\n===== RAW RESULTS: TEMPERATURE 0.0 =====")

for i, result in enumerate(temp_0_results["results"], 1):
    print(f"\nRun {i}:")
    print(result)


print("\n===== RAW RESULTS: TEMPERATURE 1.0 =====")

for i, result in enumerate(temp_1_results["results"], 1):
    print(f"\nRun {i}:")
    print(result)

===== RAW RESULTS: TEMPERATURE 0.0 =====

Run 1:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 2:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 3:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 4:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 5:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

===== RAW RESULTS: TEMPERATURE 1.0 =====

Run 1:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 2:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 3:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 4:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 5:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

In [28]:
print("===== HALLUCINATION TEST 1 =====")

test1_prompt = f"""
{LETTERS["L001"]}

What is the applicant's credit score?
"""

response1 = ask_llm(
    test1_prompt,
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0,
    max_tokens=100
)

test1_output = response1.choices[0].message.content

print(test1_output)

===== HALLUCINATION TEST 1 =====
The application does not mention the applicant's credit score. It only provides information about her business, savings, and repayment plan, as well as her guarantor.

In [29]:
print("===== HALLUCINATION TEST 2 =====")

irrelevant_text = """
Today's weather in Accra will be partly cloudy with temperatures
between 24 and 29 degrees Celsius. There may be light rain in
the afternoon. Winds will be moderate.
"""

test2_output = extract_fields(irrelevant_text)

print(test2_output)

===== HALLUCINATION TEST 2 =====
{'applicant_name': None, 'amount_ghs': None, 'purpose': None, 'monthly_profit_ghs': None, 'has_collateral_or_guarantor': False, 'repayment_months': None}

Could automated lending be unfair?
If the bank fully automated the decisions, applicants who write poorly in English could be unfairly rejected even if they operate successful businesses. The model may mistake poor writing ability for poor business ability or financial reliability. This could disadvantage applicants with limited English proficiency or different communication styles. Human review is therefore important so that the loan decision considers the applicant's actual business situation rather than only the quality of their writing.

Sending the letters to a third-party API?
Loan applications contain personal and potentially sensitive financial information. Sending this information to a third-party API in another country could create privacy, security, and data-protection risks. Before deploying the system at a real Ghanaian microfinance institution, I would check how the API provider stores and processes data, whether the data can be used for model training, where the data is stored, what security measures are provided, and whether the institution has the necessary legal and organizational permissions to send the information to that provider.

Two production safeguards?
1. Human review: The LLM should never make the final loan decision. A qualified loan officer should review the original application, the extracted information, and the LLM's recommendations before making a decision.

2. Monitoring and logging: The system should record its outputs and monitor for errors, hallucinations, inconsistent results, and potential bias. Regular audits could identify problems before they cause widespread harm.

In [30]:
print(response.usage)

CompletionUsage(completion_tokens=87, prompt_tokens=253, total_tokens=340, completion_tokens_details=None, prompt_tokens_details=None, queue_time=0.052058908, prompt_time=0.0126714, completion_time=0.347792372, total_time=0.360463772)

Section 5 
My test API call used 334 total tokens. If each application required approximately the same number of tokens, processing 1,000 applications per month would require about 334,000 tokens. This shows that token usage should be considered when choosing an API provider, especially as the number of applications increases.

1. Prompting as engineering

Iterating on prompts is similar to tuning model hyperparameters because both involve changing settings or instructions, testing the results, and evaluating whether performance improves. The difference is that prompting changes how an existing model is instructed, while hyperparameter tuning in a trained model changes aspects of how the model learns or behaves during training.

2. Trust

I would not trust this system to run completely unattended. Although the evaluation can show good accuracy and consistency, the hallucination tests demonstrate that an LLM can still produce unsupported information. The extraction accuracy and hallucination results are therefore important reasons to keep a human involved in the final loan decision.

4. API vs. training your own model

Calling a foundation model through an API is more practical for this task because training a large language model from scratch would require much more data, computing power, time, and expertise. An API provides access to an already-trained model and allows the system to be developed quickly. Training a model could be more appropriate when an organization has a large specialized dataset, strict requirements for customization, or a need to control the model and its infrastructure directly.